server:
  port: 8080

spring:
  application:
    name: todo-app

todo:
  file:
    path: ${user.home}/.todo/tasks.json

cors:
  allowed-origins: http://localhost:5173,http://localhost:3000

logging:
  level:
    root: INFO
    com.company.todo: DEBUG
    com.company.todo.repository: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
